# Generated by Django 5.0.7 on 2024-08-16 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="user_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("fileName", models.CharField(max_length=256)),
                (
                    "navigator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="myapp.navigatormodel",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="File",
        ),
    ]
