# Generated by Django 5.0.7 on 2024-08-23 04:20

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_userfiles_delete_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfiles",
            old_name="uploaded_at",
            new_name="uploadedAt",
        ),
        migrations.AlterField(
            model_name="userfiles",
            name="file",
            field=models.FileField(upload_to=myapp.models.uploadedFilePath),
        ),
    ]
